# -*- coding: utf-8 -*-
"""electron_in_electric_field.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1bkXi9F2mJAedhkEggqdjXcf8n_ZoF1
"""

import numpy as np
import matplotlib.pyplot as plt

# --- Παράμετροι (Ηλεκτρόνιο) ---
q = -1.6e-19       # Φορτίο ηλεκτρονίου (C)
m = 9.11e-31       # Μάζα ηλεκτρονίου (kg)
E = 500            # Ένταση ηλεκτρικού πεδίου (N/C)
vx = 2e6           # Αρχική οριζόντια ταχύτητα (m/s)

# --- Υπολογισμοί ---
t_max = 2e-8       # Χρόνος προσομοίωσης (πολύ μικρός για υποατομικά σωματίδια)
t = np.linspace(0, t_max, 500)

# Εξισώσεις κίνησης
x = vx * t
ay = (q * E) / m   # Επιτάχυνση στον άξονα y
y = 0.5 * ay * t**2

# --- Σχεδίαση ---
plt.figure(figsize=(10, 5))
plt.plot(x, y, label='Τροχιά ηλεκτρονίου', color='purple', lw=2)

# Σχεδίαση των πλακών του πυκνωτή
plt.axhline(0.02, color='red', lw=3, label='Θετική Πλάκα (+)')
plt.axhline(-0.02, color='blue', lw=3, label='Αρνητική Πλάκα (-)')

plt.title('Κίνηση Ηλεκτρονίου σε Ομογενές Ηλεκτρικό Πεδίο')
plt.xlabel('Απόσταση x (m)')
plt.ylabel('Απόσταση y (m)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='upper right')



plt.show()

# Εκτύπωση της τελικής απόκλισης
print(f"Η τελική απόκλιση στον άξονα y είναι: {y[-1]*1000:.2f} mm")